### ISSUE TITLE
error in build

### ISSUE THREAD

**Issue by vuteam** [mohousch/neutrinohd2#10]
Log data follows:
| DEBUG: SITE files ['endian-little', 'bit-32', 'mips-common', 'common-linux', 'common-glibc', 'mipsel-linux', 'common']
| DEBUG: Executing shell function autotools_preconfigure
| DEBUG: Shell function autotools_preconfigure finished
| DEBUG: Executing python function autotools_aclocals
| DEBUG: SITE files ['endian-little', 'bit-32', 'mips-common', 'common-linux', 'common-glibc', 'mipsel-linux', 'common']
| DEBUG: Python function autotools_aclocals finished
| NOTE: base_contains is deprecated, please use bb.utils.contains instead.
| NOTE: base_contains is deprecated, please use bb.utils.contains instead.
| NOTE: base_contains is deprecated, please use bb.utils.contains instead.
| NOTE: base_contains is deprecated, please use bb.utils.contains instead.
| NOTE: base_contains is deprecated, please use bb.utils.contains instead.
| NOTE: base_contains is deprecated, please use bb.utils.contains instead.
| DEBUG: Executing shell function do_configure
| 
| You must have libtool installed to compile neutrinohd2.
| Download the appropriate package for your system,
| or get the source from one of the GNU ftp sites
| listed in http://www.gnu.org/order/ftp.html

**Comment by lilo74** [comment]
Hi  mohousch have this error:

Build Configuration:
BB_VERSION           = "1.37.0"
BUILD_SYS            = "i686-linux"
NATIVELSBSTRING      = "ubuntu-18.04"
TARGET_SYS           = "mipsel-oe-linux"
MACHINE              = "azboxme"
DISTRO               = "openatv"
DISTRO_VERSION       = "6.2"
TUNE_FEATURES        = "o32 fpu-hard mips32"
TARGET_FPU           = ""
meta                 = "HEAD:3cf8bda5e4d4a345793aa72be97e94c41520ec01"
meta-oe              
meta-multimedia      
meta-networking      
meta-filesystems     
meta-python          
meta-webserver       = "HEAD:29a4983d5a4462d8e7b9abcd55bfb3013f578fdd"
meta-oe              = "HEAD:c899be715f6a5280f7d11751baeb8cdd3f241ea2"
meta-qt5             = "HEAD:817fc2a19b63908f0628f29c2940a1dc44563ef9"
meta-airdigital      
meta-azbox           
meta-ax              
meta-blackbox        
meta-ceryon          
meta-clap            
meta-cube            
meta-dags            
meta-dinobot         
meta-dream           
meta-ebox            
meta-edision         
meta-entwopia        
meta-formuler        
meta-fulan           
meta-gfutures        
meta-gigablue        
meta-ini             
meta-ixuss           
meta-linkdroid       
meta-broadmedia      
meta-odin            
meta-odroid          
meta-octagon         
meta-protek          
meta-skylake         
meta-tiviar          
meta-tripledot       
meta-ultramini       
meta-vuplus          
meta-wetek           
meta-xp              
meta-xtrend          
meta-xcore           = "HEAD:c899be715f6a5280f7d11751baeb8cdd3f241ea2"
meta-local           = "4.2:bcfe0722ba36fb1c63a90c0e60060da7fc7bdac9"

Initialising tasks: 100% |#######################################| Time: 0:00:18
NOTE: Executing SetScene Tasks
NOTE: Executing RunQueue Tasks
ERROR: e2fsprogs-native-1.43.7-r0 do_compile: oe_runmake failed
ERROR: e2fsprogs-native-1.43.7-r0 do_compile: Function failed: do_compile (log file is located at /home/carlos/oe-alliance/build-enviroment/builds/openatv/release/azboxme/tmp/work/i686-linux/e2fsprogs-native/1.43.7-r0/temp/log.do_compile.22340)
ERROR: Logfile of failure stored in: /home/carlos/oe-alliance/build-enviroment/builds/openatv/release/azboxme/tmp/work/i686-linux/e2fsprogs-native/1.43.7-r0/temp/log.do_compile.22340

**Comment by mohousch** [comment]
This Error comes from Host Maschine
