### ISSUE TITLE
How to???

### ISSUE THREAD

**Issue by OpenVu** [mohousch/neutrinohd2#11]
how to build neutrinohd2  with openpli???

**Comment by mohousch** [comment]
mkdir openpli
cd openpli
git clone https://github.com/OpenPLi/openpli-oe-core.git
cd openpli-oe-core
MACHINE=dm800se make image

when the build succed without errors
cd meta-openpli

git clone git://github.com/mohousch/recipes-neutrino.git

cd build

. ./env.source

bitbake neutrinohd2

bitbake neutrinohd2-plugins
